name: Feature
description: 새 기능 개발
title: "[FEAT] "
labels: ["feat"]
body:
  - type: textarea
    id: purpose
    attributes:
      label: 목적
      placeholder: "왜 이 기능이 필요한지 작성"
    validations:
      required: true

  - type: textarea
    id: work
    attributes:
      label: 작업 내용
      placeholder: |
        - 
        - 
    validations:
      required: true

  - type: textarea
    id: done
    attributes:
      label: 완료 조건
      placeholder: |
        - 
        - 
    validations:
      required: true